# Generated by Django 6.1 on 2026-08-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaperoom',
            name='room_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
