# Generated by Django 6.1 on 2026-08-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0002_alter_escaperoom_room_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeEventState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('STARTED', 'Started'), ('FINISHED', 'Finished')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
