# Generated by Django 6.1 on 2026-08-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0003_escapeeventstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='challenge',
            field=models.TextField(blank=True),
        ),
    ]
