# Generated by Django 6.1 on 2026-08-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0004_puzzle_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='hints_used',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
