# Generated by Django 6.1 on 2026-08-24 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escape', '0005_progress_hints_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscapeGameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('total_score', models.IntegerField(default=0)),
                ('remaining_time_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_puzzle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='escape.puzzle')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to='escape.escaperoom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_game_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'room', 'attempt_number')},
            },
        ),
    ]
