# Generated by Django 6.1 on 2026-08-19 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureHuntProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('completed_levels', models.JSONField(default=list)),
                ('best_scores', models.JSONField(default=dict)),
                ('total_attempts', models.IntegerField(default=0)),
                ('total_hints_used', models.IntegerField(default=0)),
                ('highest_unlocked_level', models.IntegerField(default=1)),
                ('last_played_level', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treasure_hunt_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
