# Generated by Django 6.1 on 2026-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasurehuntprogress',
            name='best_score',
            field=models.IntegerField(default=0),
        ),
    ]
