# Generated by Django 6.1 on 2026-09-02 08:32

import django_mongodb_backend.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasure_hunt', '0002_treasurehuntprogress_best_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasurehuntprogress',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
