# Generated by Django 6.1 on 2026-08-28 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MALWARE', 'Malware'), ('NETWORK', 'Network'), ('SECURITY', 'Security'), ('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('CRYPTOGRAPHY', 'Cryptography'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryGameSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('EXPERT', 'Expert')], max_length=10, unique=True)),
                ('grid_size', models.PositiveIntegerField()),
                ('time_limit_seconds', models.PositiveIntegerField(default=180)),
                ('points_per_pair', models.PositiveIntegerField(default=100)),
                ('wrong_move_penalty', models.PositiveIntegerField(default=5)),
                ('hint_penalty', models.PositiveIntegerField(default=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryBestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_best', models.PositiveIntegerField(default=0)),
                ('medium_best', models.PositiveIntegerField(default=0)),
                ('hard_best', models.PositiveIntegerField(default=0)),
                ('expert_best', models.PositiveIntegerField(default=0)),
                ('total_best', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_best_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
