# Generated by Django 6.1 on 2026-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorycard',
            name='category',
            field=models.CharField(choices=[('MALWARE', 'Malware'), ('NETWORK', 'Network'), ('SECURITY', 'Security'), ('ATTACK', 'Attack'), ('DEFENSE', 'Defense'), ('CRYPTOGRAPHY', 'Cryptography'), ('PROGRAMMING', 'Programming')], default='OTHER', max_length=30),
        ),
    ]
